version: '3.8'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8082:8080"
      - "8083:8081"
    command: mitmweb --web-host 0.0.0.0 --set web_password=mysecretpass
    volumes:
      - ./mitmproxy/certs:/home/mitmproxy/.mitmproxy   

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"  # OTLP HTTP endpoint